import { Router } from "express";
import { storage } from "../storage";
import OpenAI from "openai";

export const chatbotRouter = Router();

// Initialize OpenAI API client
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// System message that instructs the AI how to behave
const systemMessage = `You are a sustainability assistant specialized in eco-friendly web development practices. 
Your purpose is to help developers build more environmentally friendly websites and applications.

Your knowledge focuses on:
1. Website carbon footprint analysis and reduction
2. Green hosting providers and their benefits
3. Performance optimization techniques for sustainability
4. Sustainable web design principles
5. Energy-efficient coding practices
6. Asset optimization (images, videos, scripts, etc.)
7. Measuring and monitoring website environmental impact
8. Industry standards for sustainable web development

Always be helpful, concise, and provide practical advice that developers can implement.
If you don't know something specific about sustainable web development, acknowledge that and suggest related topics you can help with.`;

// Sample sustainability tips for the random tip feature
const sustainabilityTips = [
  "Switch to a green hosting provider to reduce your carbon footprint by up to 40%.",
  "Compress images using modern formats like WebP to reduce file sizes by up to 30%.",
  "Implement a CDN to reduce data transfer distances and lower energy consumption.",
  "Minimize HTTP requests by combining CSS and JavaScript files.",
  "Use system fonts instead of custom fonts to reduce page weight.",
  "Implement proper caching policies to reduce server load and bandwidth usage.",
  "Choose dark mode for your website to save energy on OLED screens.",
  "Remove unused CSS and JavaScript to reduce file sizes.",
  "Optimize your database queries to reduce server processing time.",
  "Use lazy loading for images and videos to reduce initial page load size."
];

const knowledgeBase = {
  "green hosting": "Green hosting providers use renewable energy sources like wind or solar power to run their data centers, significantly reducing the carbon footprint of your website. Some popular green hosting providers include GreenGeeks, A2 Hosting, and DreamHost.",
  
  "carbon footprint": "A website's carbon footprint is the amount of CO2 generated by the electricity needed to power the servers, network infrastructure, and user devices. The average webpage produces 1.76g of CO2 per page view.",
  
  "image optimization": "Image optimization involves compressing images, using appropriate formats (like WebP), and implementing responsive images to serve different sizes based on the user's device. This reduces file sizes, load times, and energy consumption.",
  
  "caching": "Caching stores copies of files or data so they can be served faster on subsequent requests. This reduces server processing time, bandwidth usage, and energy consumption, making your website more sustainable.",
  
  "performance optimization": "Performance optimization improves loading times and reduces resource usage. Techniques include minifying code, optimizing images, implementing caching, and reducing HTTP requests, all of which contribute to a more sustainable website.",
  
  "sustainability badges": "Sustainability badges in web development signal a commitment to eco-friendly practices. Our platform offers badges for achievements like switching to green hosting, optimizing resources, and reducing overall carbon emissions.",
  
  "lazy loading": "Lazy loading delays the loading of non-critical resources until they're needed, reducing initial page load size and resource consumption, making your website more environmentally friendly."
};

// Simple natural language processing to find the most relevant knowledge base entry
function findRelevantKnowledgeBase(question: string): string {
  question = question.toLowerCase();
  
  // Check for exact matches first
  for (const [key, value] of Object.entries(knowledgeBase)) {
    if (question.includes(key)) {
      return value;
    }
  }
  
  // If no exact match, find the closest match
  let bestMatch = "";
  let highestScore = 0;
  
  for (const key of Object.keys(knowledgeBase)) {
    const words = key.split(" ");
    let score = 0;
    
    for (const word of words) {
      if (question.includes(word)) {
        score += 1;
      }
    }
    
    if (score > highestScore) {
      highestScore = score;
      bestMatch = key;
    }
  }
  
  if (highestScore > 0) {
    return knowledgeBase[bestMatch as keyof typeof knowledgeBase];
  }
  
  // If no relevant match found, return a general sustainability tip
  return sustainabilityTips[Math.floor(Math.random() * sustainabilityTips.length)];
}

// Generate AI response using OpenAI API
async function generateResponse(message: string): Promise<string> {
  try {
    // First check if the API key is available
    if (!process.env.OPENAI_API_KEY) {
      console.warn("OpenAI API key is missing. Using fallback response.");
      return useFallbackResponse(message);
    }

    // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemMessage },
        { role: "user", content: message }
      ],
      temperature: 0.7,
      max_tokens: 500,
    });

    return response.choices[0]?.message?.content?.trim() || "I'm having trouble processing your request at the moment. Please try again.";
  } catch (error) {
    console.error("OpenAI API error:", error);
    // Provide a graceful fallback if the API call fails
    return useFallbackResponse(message);
  }
}

// Fallback response method when API is not available
function useFallbackResponse(message: string): string {
  const greetings = ["hello", "hi", "hey", "greetings"];
  const questions = ["how", "what", "why", "when", "where", "which", "who", "can", "could"];
  const aboutWebsite = ["website", "web", "site", "page", "online"];
  const aboutCarbon = ["carbon", "footprint", "emissions", "co2", "greenhouse"];
  const aboutOptimization = ["optimize", "optimization", "improve", "reduce", "speed", "performance"];
  
  message = message.toLowerCase();
  
  // Check for greetings
  if (greetings.some(greeting => message.includes(greeting))) {
    return "Hello! I'm your sustainability assistant. How can I help you make your web development more eco-friendly today?";
  }
  
  // Check for questions about carbon footprint
  if (questions.some(q => message.includes(q)) && aboutCarbon.some(term => message.includes(term))) {
    return findRelevantKnowledgeBase("carbon footprint");
  }
  
  // Check for questions about website optimization
  if (aboutOptimization.some(term => message.includes(term)) && aboutWebsite.some(term => message.includes(term))) {
    return findRelevantKnowledgeBase("performance optimization");
  }
  
  // Check for general knowledge base matches
  for (const key of Object.keys(knowledgeBase)) {
    if (message.includes(key)) {
      return knowledgeBase[key as keyof typeof knowledgeBase];
    }
  }
  
  // Try to find a relevant response from the knowledge base
  const knowledgeResponse = findRelevantKnowledgeBase(message);
  if (knowledgeResponse) {
    return knowledgeResponse;
  }
  
  // Fallback response
  return "I'm not sure how to respond to that question about web sustainability. You might want to try asking about green hosting, carbon footprint, or how to optimize your website's performance.";
}

// Get chat history (protected route)
chatbotRouter.get("/history", async (req, res) => {
  if (!req.isAuthenticated()) {
    return res.status(401).json({ message: "Authentication required" });
  }
  
  try {
    const messages = await storage.getChatMessagesByUserId(req.user.id);
    res.json(messages);
  } catch (error) {
    console.error("Chat history retrieval error:", error);
    res.status(500).json({ message: "Failed to retrieve chat history" });
  }
});

// Send message to chatbot (protected route)
chatbotRouter.post("/send", async (req, res) => {
  if (!req.isAuthenticated()) {
    return res.status(401).json({ message: "Authentication required" });
  }
  
  try {
    const { message } = req.body;
    
    if (!message) {
      return res.status(400).json({ message: "Message is required" });
    }
    
    // Store user message
    const userMessage = await storage.createChatMessage({
      userId: req.user.id,
      content: message,
      role: "user"
    });
    
    // Generate AI response using OpenAI API
    const aiResponseContent = await generateResponse(message);
    
    // Store AI response
    const aiMessage = await storage.createChatMessage({
      userId: req.user.id,
      content: aiResponseContent,
      role: "assistant"
    });
    
    res.json({
      userMessage,
      aiMessage
    });
  } catch (error) {
    console.error("Chat message error:", error);
    res.status(500).json({ message: "Failed to process chat message" });
  }
});

// Get a random sustainability tip (protected route)
chatbotRouter.get("/tip", async (req, res) => {
  if (!req.isAuthenticated()) {
    return res.status(401).json({ message: "Authentication required" });
  }
  
  try {
    const randomTip = sustainabilityTips[Math.floor(Math.random() * sustainabilityTips.length)];
    res.json({ tip: randomTip });
  } catch (error) {
    console.error("Tip retrieval error:", error);
    res.status(500).json({ message: "Failed to retrieve sustainability tip" });
  }
});
